---
#A playbook to git commit and push - because typing commands is hard
#Assumes remote origin and master are set
#Assumes git-credential store is enabled and credentials to git are stored
  - hosts: control
    vars:
       gitComment: Updated
    
    vars_prompt:
     - name: gitComment
       prompt: Git commit comment
       private: no

    tasks:
     - name: Add all files to git push
       shell: git add .
      
     - name: Commit all files with the comment you gave
       shell: "git commit -m '{{ gitComment }}'"
      
     - name: Pull all new files from master
       shell: git pull origin master
      
     - name: Push all files to remote
       shell: git push origin master
      
